### ISSUE TITLE
Examine version needed to extract

### ISSUE THREAD

**Issue by mvdnes** [zip-rs/zip-old#154]
Whilst reading the EPUB specification, I noticed this text in [Section 4.2](https://www.w3.org/publishing/epub3/epub-ocf.html#confreq-zip-fld-version):

> In the local file header table, OCF ZIP Containers MUST set the `version needed to extract` fields to the values `10`, `20` or `45` in order to match the maximum version level needed by the given file (e.g., `20` if Deflate is needed, `45` if ZIP64 is needed). OCF Processors MUST treat any other values as being in error.

Currently, the library will set it to `20` when using stored or deflate compression, and 46 when using bzip2. We might want to specify `10` for using stored compression, and examine if the value is correct in other cases as well.

Also, if and when we will support writing ZIP64, we should also increase this number to at least 45 when it is used.

**Comment by Plecra** [comment]
While reading and writing are we making sure the version information all checks out? I'd love to evaluate all the version identifiers given by the APPNOTE

**Comment by Pr0methean** [comment]
Fixed in 2.1.1.
