### ISSUE TITLE
There is no supported API for writing file Paths into zip archives

### ISSUE THREAD

**Issue by magnalite** [zip-rs/zip-old#253]
It appears that archives zipped on Windows keep the usage of a `\` in their paths. This is fine when extracting on Windows but if you try to extract the zip on a unix system it will output a flattened file structure containing `\`s in the files names instead of in sub-directories. Instead all zip files should internally only contain paths using `/`s as this remains compatible when extracted on both Windows and unix.

**Comment by Plecra** [comment]
Yup, this is a problem. `start_file` take the exact value for the name of the zip file, because zip file names are unstructured by default. However it's much more common to want directories to be well behaved, and we don't make it easy to use `Path`s correctly when writing a zip file.

**Comment by zamazan4ik** [comment]
Am I right that we can try to backport a fix from `start_file_from_path` to the new API?

**Comment by Plecra** [comment]
Kind of. The only question is whether we should - it's definitely not ideal to treat `String`s as paths and rewrite directory slashes: maybe the user really wanted a slash in their filename!

The solution is probably fixing, and then undeprecating `*_from_path`. Then pointing users to the right API. Whoops 🤦

**Comment by Pr0methean** [comment]
Fixed in version 1.1.1.
