### ISSUE TITLE
Use BufReader read encrypt zip has error: corrupt deflate stream

### ISSUE THREAD

**Issue by zjzdy** [zip-rs/zip-old#280]
When I use `zip::ZipArchive::new(BufReader::new(File::open(zip_path).unwrap()))` to open file, decompress happen error: `Custom { kind: InvalidInput, error: "corrupt deflate stream" }`. But `zip::ZipArchive::new(File::open(zip_path).unwrap())` is ok.
Version: `zip = "0.5.13"` (The git version also has the problem.)
toolchain: stable-x86_64-pc-windows-msvc
rustc 1.58.1 (db9d1b20b 2022-01-20)
The file compress by 7z.
Password: 52gv
Code and Data: [testzip.zip](https://github.com/zip-rs/zip/files/8190975/testzip.zip)
Only zip file: [data.zip](https://github.com/zip-rs/zip/files/8190976/data.zip)

Code:
```rust
use std::fs::File;
use std::io::{BufReader, Read};

fn main() {
    let zip_path = "data.zip";
    let result = zip::ZipArchive::new(BufReader::new(File::open(zip_path).unwrap()));
    if let Ok(mut archive) = result {
        for index in 0..archive.len() {
            let result = archive.by_index_decrypt(index, "52gv".as_ref());
            if let Ok(Result::Ok(mut zipfile)) = result {
                println!("{}:{}", zipfile.name(), zipfile.size());
                let mut buff = [0u8; 1024*8];
                loop {
                    let size = zipfile.read(&mut buff).unwrap();
                    if size == 0 {
                        break;
                    }
                }
            }
        }
    }
}
```

**Comment by zamazan4ik** [comment]
@Plecra Do you know anything about the bug? Maybe we had something similar before.

**Comment by Plecra** [comment]
Doesn't look familiar. It'll be a problem with how we're feeding the decrypted data through
