### ISSUE TITLE
Can't distinguish between files and directories with the same name that are extracted?

### ISSUE THREAD

**Issue by San-greal** [zip-rs/zip-old#376]
The zip format file is generated with the following code:

```rust
let path = Path::new("test.zip");
let file = File::create(path).unwrap();

let mut zip = ZipWriter::new(file);
let options = FileOptions::default().compression_method(Zstd);
zip.start_file("test", options).unwrap();
zip.write_all(b"Hello, World!\n").unwrap();
zip.write_all(b"Hello, World!\n").unwrap();
zip.add_directory("test/test1", options).unwrap();
zip.finish().unwrap();
```

The unzip operation is performed by:

```rust
let mut file = File::open("test.zip").unwrap();
let mut archive = zip::ZipArchive::new(file).unwrap();
archive.extract("C:\\Users\\Desktop\\untitled\\src").unwrap();
```

So the following results appear:
![image](https://github.com/zip-rs/zip/assets/25400257/47779377-0039-407c-a1ed-299053ca4ee6)

There is no problem when the directory created is not `test/test1`, for example `a/test1` is correct. Is this caused by the inability to distinguish between files and directories?

**Comment by ryanavella** [comment]
Am I understanding correctly that the error only happens during unzipping, when trying to create both a `test` file and a `test/` directory?

I'm fairly certain most mainstream OS+filesystem combinations don't allow this. On Unix-like systems, directories are just another kind of file, so this would be like trying to name two files the same thing.
