### ISSUE TITLE
Unneeded import for ZipWriter docs

### ISSUE THREAD

**Issue by OscarCreator** [zip-rs/zip-old#391]
In `ZipWriter` there is an unneeded import
https://github.com/zip-rs/zip/blob/21a20584bc9e05dfa4f3c5b0bc420a1389fae2c3/src/write.rs#L77C9-L77C37

**Comment by Pr0methean** [comment]
Fixed by https://github.com/zip-rs/zip2/commit/66e0b825290d7da2ea399c15ac2b5bc06339e6ae. If you still see an issue, please reopen it at https://github.com/zip-rs/zip2, since this repo is no longer maintained.
