### ISSUE TITLE
Better examples for reading a zip

### ISSUE THREAD

**Issue by xTachyon** [zip-rs/zip-old#415]
My guess is that the most common case for using a zip crate is to read a zip file. Given this assumption, I feel like one of the first things the user should see on the docs on docs.rs is an example of reading a zip file and printing the file names, or something of the sort. The examples directory is good, but it's not mentioned at all on docs.rs.

Another thing that isn't immediately obvious is that the crate does no buffering whatsoever, and the user should probably use a `BufReader` when reading from a `File`. In my case, the unbuffered version took 11s to `new` the object, while the buffered version took only about 500ms.

**Comment by Pr0methean** [comment]
This repo is no longer maintained. This issue has been partly resolved by https://github.com/zip-rs/zip2/pull/55 and should be fully resolved by https://github.com/zip-rs/zip2/pull/56, https://github.com/zip-rs/zip2/pull/59 and https://github.com/zip-rs/zip2/pull/67.
