### ISSUE TITLE
Is it possible  to make ZipFile seekable?

### ISSUE THREAD

**Issue by Leojangh** [zip-rs/zip-old#424]
The [zip::read::ZipFile](https://docs.rs/zip/0.6.6/zip/read/struct.ZipFile.html).
My geuss is impossible.

**Comment by RandomInsano** [comment]
I'm just passing by, but searching for existing issues that contain "Seek" provided this:
https://github.com/zip-rs/zip/issues/223

**Comment by Pr0methean** [comment]
Duplicate of #223.
