### ISSUE TITLE
panic when trying to exhaust the stream

### ISSUE THREAD

**Issue by wolfv** [zip-rs/zip-old#432]
The Drop implementation of `ZipFile` currently panic's when the stream has an issue. Unfortunately we hit this panic sometimes when passing in a reqwest stream into the zipfile (using the `read_zipfile_from_stream` function).

Would it not be better to ignore errors?

https://github.com/zip-rs/zip/blob/3e88fe66c941d411cff5cf49778ba08c2ed93801/src/read.rs#L1008

Any further operations would anyways error with this particular stream...

**Comment by Pr0methean** [comment]
Please reopen this against https://github.com/zip-rs/zip2 if it's not fixed in https://github.com/zip-rs/zip2/pull/48. This repo is no longer maintained.
