### ISSUE TITLE
Path separator handling on Windows

### ISSUE THREAD

**Issue by mistydemeo** [zip-rs/zip-old#439]
It looks like the ZIP format expects to always get `/` as path separators, so passing in Windows paths without normalization produces some broken/unexpected ZIP files. It looks like in #103 this was fixed by adding `start_file_from_path` and `add_directory_from_path`, but they were deprecated without replacement in #182. Is the recommended approach for users to normalize all paths to Unix file separators before passing the filenames in to `write_file` or `add_directory`?

**Comment by Pr0methean** [comment]
Per APPNOTE:
> 4.4.17.1 The name of the file, with optional relative path. The path stored MUST not contain a drive or device letter, or a leading slash. All slashes MUST be forward slashes '/' as opposed to backwards slashes '\' for compatibility with Amiga and UNIX file systems etc. If input came from standard input, there is no file name field.

**Comment by Pr0methean** [comment]
Version 1.1.1 will undeprecate `start_file_from_path` and `add_directory_from_path` and add `add_symlink_from_path`. It also normalizes `.` and `..`.

**Comment by Pr0methean** [comment]
@mistydemeo Could you please confirm that version 1.1.1 works for you, and then close this issue? I can't do so myself because I'm still waiting on @Plecra to add me as a repo admin.

**Comment by mistydemeo** [comment]
Oh, sure! What's the situation with the transfer of ownership? I was surprised to see crates.io updated to point at a new git repo without much comment, or a note in this repo.

**Comment by Pr0methean** [comment]
That note is coming in https://github.com/zip-rs/zip/pull/447, but I've also asked @Plecra to make me a repo admin so that I can change the name to `zip-old`, close issues and PRs as I fix or copy them in my repo, and then archive this repo once all issues and PRs are closed.
